<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <div class="logo-nav">
                <a href="http://bnp.ba">
                    <img src="<?php echo App::getSkinUrl();?>/images/logo-web.png" />
                </a>
            </div>
            <div class="site-name hidden-sm hidden-xs">

                <a class="navbar-brand page-scroll" href="http://bnp.ba">
                    <b>BNP ZENICA</b>
                    <br>
                    <span class="small">BOSANSKO NARODNO POZORIŠTE ZENICA</span>
                </a>
            </div>

        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="<?php echo App::getBaseUrl(); ?>"><i class="fa fa-home" aria-hidden="true"></i></a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pomoć <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?php echo App::getBaseUrl()."/doc/Instrukcije_za_pisanje_motivacionog_pisma.pdf"; ?>" target="_blank">Instrukcije za pisanje motivacionog pisma</a></li>
                        <li><a href="<?php echo App::getBaseUrl()."/doc/CV_Evropski_format.pdf"; ?>" target="_blank">CV - Evropski format</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>