<div class="sidebar-image">
    <img src="<?php echo App::getSkinUrl();?>images/sign-contract.jpg" class="img-responsive" />
</div>
<h2>Saradnja sa BNP Zenica</h2>
<div class="sidebar-text">
<p>Bosansko narodno pozorište Zenica je javna ustanova, koja već godinama otvorena za sve konkretne i korisne vrste saradnje, koje će biti od koristi mladim ljudima i podržavati njihove talente, želje i sposobnosti.</p>
<p>Već godinama podržavamo studente i nudimo im saradnju u kojoj imaju priliku da uče, stječu nove sposobnosti, upoznaju se s radom Bosanskog narodnog pozorišta Zenica, ali i pomjeraju vlastite granice.</p>
<p>Cilj nam je da za svaku mladu osobu, kojoj je u fokusu interesovanja teatarska umjetnost, nađemo način na koji će sarađivati sa našom teatarskom kućom, te tako osnažiti svoje sposobnosti i stjecati svoja prva radna/volonteska iskustva, koja će im biti od koristi u narednom periodu.</p>
</div>