<ul class="nav nav-sidebar">
    <li class="active"><a href="<?php echo App::getUrl('/help'); ?>">Help Dashboard<span class="sr-only">(current)</span></a></li>
    <li><a href="<?php echo App::getUrl('/help/index/info'); ?>">Info</a></li>
    <li><a href="<?php echo App::getUrl('/help/layout'); ?>">Layout</a></li>
    <li><a href="<?php echo App::getUrl('/help/module'); ?>">Module</a></li>
    <hr>
    <li><a href="<?php echo App::getUrl('/help/debug'); ?>">Debug</a></li>
</ul>
