<?php $content = $this->getContent();?>
<!DOCTYPE html>
<html lang="en">
<head>
    <!--template/html/head.phtml-->
    <?php $this->getHead()->render(); ?>
    <title><?php echo $content->getTitle(); ?></title>
</head>

<body>

<!--Navbar-->
<?php $this->getNavbar()->render(); ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12 main">
            <!-- Main Content -->
            <?php $this->getContent()->render(); ?>
        </div>
    </div>
</div>
<!-- js files -->
<?php $this->getBottom()->render(); ?>
</body>
</html>
